### ISSUE TITLE
Invite System: player receives email even if not invited

### ISSUE THREAD

**Issue by NicoWeidmann** [cs-select-team/CS-Select#69] opened 2019-02-05 15:26 UTC
After creating a game and inviting email address "test", another user registered under a regular email address received an invitation email.

**Comment by Weitspringer** [comment] 2019-02-06 14:31
Found the reason:
The GameCreator class only reads from GameOption's attribute "invited Emails", but does not empty it.
So we could use a Map which binds an Email to a boolean, which are set all to "false" after the game has been created. When inviting a player whilst in gamecreation interface, according boolean will be set to true or a new entry is made in the Map if this Email was not invited yet (from the one organiser who creates the game)

**Comment by Weitspringer** [comment] 2019-02-08 23:13
I implemented that HashSet which holds invited Emails resets after each gamecreation if it wasn't empty already.

**Comment by SeineEloquenz** [comment] 2019-02-11 16:01
Does this still occur or can this be closed @Weitspringer?

**Comment by Weitspringer** [comment] 2019-02-12 14:18
Does not work

**Comment by Weitspringer** [comment] 2019-02-12 14:19
Looking into it

**Comment by Weitspringer** [comment] 2019-02-12 14:58
@bendixsonnenberg Could that be that the frontend does not load the Emails from GameOptions after each doCreate-call? Should do the trick

**Comment by bendixsonnenberg** [comment] 2019-02-12 15:00
could you explain what you mean by that? In more detail if possible

**Comment by Weitspringer** [comment] 2019-02-12 15:02
After each creation, the list of invited Players in the Vue instance is not emptied. So if I invite a player to a game, create that game, stay on the page and create another game without inviting players, this email I typed in will be invited.

**Comment by Weitspringer** [comment] 2019-02-12 15:02
I will change that very quickly

**Comment by bendixsonnenberg** [comment] 2019-02-12 15:03
if that is the reason it should no longer be a problem, since the new way of creating games show the invited players in the invitation textarea

**Comment by bendixsonnenberg** [comment] 2019-02-12 15:05
don't change it, the values are supposed to stay in place

> I will change that very quickly

**Comment by Weitspringer** [comment] 2019-02-12 15:06
Can you explain me this in detail?

**Comment by Weitspringer** [comment] 2019-02-12 15:07
We have a single invitation area and a multi invitation area. In the single area there is nothing displayed

**Comment by bendixsonnenberg** [comment] 2019-02-12 15:08
but in the multi area all invited players are displayed.
I can add a list of all invited players if that helps you, but do not just delete the values

**Comment by Weitspringer** [comment] 2019-02-12 15:08
I won't

**Comment by Weitspringer** [comment] 2019-02-12 15:13
It is not due to the frontend...

**Comment by Weitspringer** [comment] 2019-02-12 15:17
Can anyone reproduce this? 
- Create a normal game, invite player1@cs-select.com
- Reload page
- Create a second game, only invite player2@cs-select.com
- Take a look at the Workbench. First player is invited to second game

![screenshot 20](https://user-images.githubusercontent.com/35311367/52645554-4912d100-2ee1-11e9-8333-4c453ef80af8.png)

![screenshot 21](https://user-images.githubusercontent.com/35311367/52645693-8b3c1280-2ee1-11e9-8630-b6a23042c25f.png)

![screenshot 22](https://user-images.githubusercontent.com/35311367/52645719-968f3e00-2ee1-11e9-8d8b-b3895078ef0e.png)

**Comment by Weitspringer** [comment] 2019-02-13 01:29
Or you could simply set multi field as shown field when loading page/load pattern

**Comment by Weitspringer** [comment] 2019-02-20 10:40
@SeineEloquenz @Santaaa348 Can you reproduce this?

**Comment by Santaaa348** [comment] 2019-02-20 10:45
Yes.

**Comment by Weitspringer** [comment] 2019-02-21 14:34
Because I cant

**Closed** 2019-03-08 23:22 UTC
Labels: bug
